[MemoryParameters]
channels = 1
ranks = 2
bankgroups = 8
banks_per_group = 4
rows = 65536
columns = 2048

# 256 GiB = 262144 MiB
channel_size_mb = 262144
dram_size_mb = 262144

transaction_queue_length = 4
cmd_queue_length = 4
cmd_queue_per = system
tCK = 0.3125
CL   = 175    
CWL  = 137
tRCD = 175   
tRP  = 175    
tRAS = 410    
tWR  = 137   
tRTP = 46     
tCCD_S = 15   
tCCD_L = 30   
tRRD_S = 15   
tRRD_L = 30   
tRTRS = 4     

address_mapping = rochrababgco

