[MemoryParameters]
channels = 8
ranks = 2
bankgroups = 8
banks_per_group = 4
rows = 65536
columns = 2048

# 64 GiB per DIMM/channel
# 64 GiB = 65536 MiB
channel_size_mb = 65536
dram_size_mb = 65536

transaction_queue_length = 32
cmd_queue_length = 8
cmd_queue_per = bank

tCK = 0.3125
CL   = 46      
CWL  = 36      
tRCD = 46     
tRP  = 46      
tRAS = 108     
tWR  = 36
tRTP = 12
tCCD_S = 4
tCCD_L = 8
tRRD_S = 4
tRRD_L = 8
tRTRS = 1

address_mapping = rochrababgco

